#!/bin/bash
# Phase 1 orchestrator: sync all data sources
# Called by launchd agent (hourly) and /daily-sync-all skill (on demand)
#
# Data steps (run every hour):
#   1.  ensure_daily_note.sh        - create today's note if missing
#   2.  pkm-sync sync --since 1d    - Gmail, Drive, Slack, Calendar, Jira
#   3.  normalize + create People   - two-pass attendee normalization
#   4.  sync_daily_calendar.sh      - update Meetings table in daily note
#   5.  sync_daily_work.py          - JIRA + PR notes
#   6.  project_sync.py             - enrich Project notes with related items
#   7.  pkm-sync index --since 1d   - update vector embeddings
#
# Agent steps (run at 8am, 12pm, 5pm only — or with --force-agents):
#   8.  project-tracker agent       - Meeting Prep + Active Projects + Deadlines
#   9.  daily-curator agent         - Digest + Action Items
#   10. dossier-synthesizer agent   - People dossier updates
#   11. conversation-summarizer     - Slack DMs + email summaries
#
# Flags:
#   --skip-index     Skip step 7 (vector indexing)
#   --force-agents   Run agent steps regardless of time-of-day
#   --data-only      Skip agent steps entirely
#   --agents-only    Skip data steps, run agents immediately (implies --force-agents)

set -u

_find_vault_root() {
    local dir
    dir="$(cd "$(dirname "$0")" && pwd)"
    while [ "$dir" != "/" ]; do
        [ -d "$dir/.obsidian" ] && echo "$dir" && return
        dir="$(dirname "$dir")"
    done
    echo "ERROR: Could not find vault root (no .obsidian/ directory found)" >&2
    exit 1
}
VAULT_DIR="${VAULT_DIR:-$(_find_vault_root)}"

_find_uv() {
    if command -v uv &>/dev/null; then command -v uv
    elif [ -x "$HOME/.local/bin/uv" ]; then echo "$HOME/.local/bin/uv"
    elif [ -x "/opt/homebrew/bin/uv" ]; then echo "/opt/homebrew/bin/uv"
    elif [ -x "/usr/local/bin/uv" ]; then echo "/usr/local/bin/uv"
    else echo "uv"; fi
}
UV="${UV:-$(_find_uv)}"

SKILL_DIR="$VAULT_DIR/.claude/skills/daily-sync-all"
CALENDAR_SYNC="$VAULT_DIR/.claude/skills/daily-calendar-sync/sync_daily_calendar.sh"
WORK_SYNC="$VAULT_DIR/.claude/skills/daily-work-sync/scripts/sync_daily_work.py"
if [ "$(uname)" = "Darwin" ]; then
    LOG_DIR="${LOG_DIR:-$HOME/Library/Logs/daily-work-sync}"
else
    LOG_DIR="${LOG_DIR:-/tmp/daily-work-sync}"
fi

SKIP_INDEX=false
FORCE_AGENTS=false
DATA_ONLY=false
AGENTS_ONLY=false
for arg in "$@"; do
    [ "$arg" = "--skip-index" ] && SKIP_INDEX=true
    [ "$arg" = "--force-agents" ] && FORCE_AGENTS=true
    [ "$arg" = "--data-only" ] && DATA_ONLY=true
    [ "$arg" = "--agents-only" ] && AGENTS_ONLY=true && FORCE_AGENTS=true
done

# Agent steps run at 8am, 12pm, and 5pm (±30min window)
should_run_agents() {
    if [ "$DATA_ONLY" = true ]; then return 1; fi
    if [ "$FORCE_AGENTS" = true ]; then return 0; fi
    local hour=$(date +%H)
    # 7:30-8:30, 11:30-12:30, 16:30-17:30
    case "$hour" in
        07|08|11|12|16|17) return 0 ;;
        *) return 1 ;;
    esac
}

# Check if a section in today's daily note was updated recently (within N minutes)
section_is_fresh() {
    local section_marker="$1"
    local max_age_min="${2:-120}"
    local daily_note
    daily_note="$VAULT_DIR/daily/$(date +%Y)/$(date +%m-%B)/$(date +%Y-%m-%d-%A).md"
    [ ! -f "$daily_note" ] && return 1
    # Check for timestamp like "Auto-generated by ... on YYYY-MM-DD HH:MM" or "Auto-curated on YYYY-MM-DD HH:MM"
    local ts
    ts=$(grep -A2 "$section_marker" "$daily_note" 2>/dev/null | grep -oE '[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}' | tail -1)
    [ -z "$ts" ] && return 1
    local ts_epoch now_epoch
    if date -j -f "%Y-%m-%d %H:%M" "$ts" "+%s" &>/dev/null; then
        ts_epoch=$(date -j -f "%Y-%m-%d %H:%M" "$ts" "+%s")
    else
        ts_epoch=$(date -d "$ts" "+%s" 2>/dev/null || echo 0)
    fi
    now_epoch=$(date +%s)
    local age_min=$(( (now_epoch - ts_epoch) / 60 ))
    [ "$age_min" -lt "$max_age_min" ]
}

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"
}

step() {
    echo ""
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] ─── $* ───"
}

log "=== Daily Sync All: Started ==="

if [ "$AGENTS_ONLY" = true ]; then
    log "Running agents-only mode (skipping data steps 1-7)"
fi

if [ "$AGENTS_ONLY" = false ]; then

# Step 1: Ensure daily note exists
step "Step 1/12: Ensuring today's daily note exists"
bash "$SKILL_DIR/scripts/ensure_daily_note.sh" \
    || log "WARNING: ensure_daily_note had errors (non-fatal)"

# Step 2: pkm-sync sync (Gmail archive, Drive, Slack, Calendar, Jira)
step "Step 2/12: pkm-sync sync --since 1d"
if command -v pkm-sync &>/dev/null; then
    pkm-sync sync --since 1d \
        || log "WARNING: pkm-sync sync had errors (non-fatal)"
else
    log "WARNING: pkm-sync not found in PATH, skipping"
fi

# Step 3a: Normalize attendees in pkm-sync meeting notes (pass 1)
step "Step 3a/12: Normalize attendee identifiers in meeting notes (pass 1)"
NORMALIZE_ATTENDEES="$VAULT_DIR/.claude/skills/calendar-sync-lib/normalize_attendees.py"
if [ -f "$NORMALIZE_ATTENDEES" ]; then
    python3 "$NORMALIZE_ATTENDEES" "$VAULT_DIR/Meetings/" \
        || log "WARNING: normalize_attendees had errors (non-fatal)"
else
    log "WARNING: $NORMALIZE_ATTENDEES not found, skipping"
fi

# Step 3b: Auto-create People pages for unresolved attendees
step "Step 3b/12: Auto-create People pages for unresolved attendees"
CREATE_PEOPLE="$VAULT_DIR/.claude/skills/calendar-sync-lib/create_people_pages.py"
if [ -f "$CREATE_PEOPLE" ]; then
    python3 "$CREATE_PEOPLE" "$VAULT_DIR/Meetings/" \
        || log "WARNING: create_people_pages had errors (non-fatal)"
else
    log "WARNING: $CREATE_PEOPLE not found, skipping"
fi

# Step 3c: Re-run normalize_attendees to resolve newly-created People pages
step "Step 3c/12: Normalize attendee identifiers in meeting notes (pass 2)"
if [ -f "$NORMALIZE_ATTENDEES" ]; then
    python3 "$NORMALIZE_ATTENDEES" "$VAULT_DIR/Meetings/" \
        || log "WARNING: normalize_attendees (pass 2) had errors (non-fatal)"
fi

# Step 4: Calendar sync → Meetings table in daily note
step "Step 4/12: Calendar sync"
if [ -f "$CALENDAR_SYNC" ]; then
    bash "$CALENDAR_SYNC" \
        || log "WARNING: calendar sync had errors (non-fatal)"
else
    log "WARNING: $CALENDAR_SYNC not found, skipping"
fi

# Step 5: Work sync (JIRA + GitHub PRs)
step "Step 5/12: Work sync (JIRA + PRs)"
if [ -f "$WORK_SYNC" ]; then
    "$UV" run "$WORK_SYNC" "$VAULT_DIR" \
        || log "WARNING: work sync had errors (non-fatal)"
else
    log "WARNING: $WORK_SYNC not found, skipping"
fi

# Step 6: Project sync (Related Items sections)
step "Step 6/12: Project sync"
PROJECT_SYNC="$VAULT_DIR/.claude/skills/project-sync/scripts/project_sync.py"
if [ -f "$PROJECT_SYNC" ]; then
    "$UV" run "$PROJECT_SYNC" "$VAULT_DIR" \
        || log "WARNING: project sync had errors (non-fatal)"
fi

# Step 7: Update vector index
if [ "$SKIP_INDEX" = true ]; then
    step "Step 7/12: Skipping vector index (--skip-index)"
else
    step "Step 7/12: pkm-sync index --since 1d"
    if command -v pkm-sync &>/dev/null; then
        pkm-sync index --since 1d \
            || log "WARNING: pkm-sync index had errors (non-fatal)"
    else
        log "WARNING: pkm-sync not found in PATH, skipping index"
    fi
fi

fi # end AGENTS_ONLY guard for data steps 1-7

# --- Agent steps (time-gated: 8am, 12pm, 5pm or --force-agents) ---
# Dependency-based ordering:
#   Phase 1 (independent): meeting-prepper, conversation-summarizer
#   Phase 2 (independent): project-updater (writes Projects/*.md)
#   Phase 3 (dependent):   daily-summarizer (needs 8a), daily-curator (needs all above)
# Dossier runs on its own daily schedule via run_dossier.sh
export AGENT_TRIGGER="scheduled"
AGENT_RUNNER="$SKILL_DIR/scripts/run_agent.py"

if should_run_agents; then
    log "Agent window active (hour=$(date +%H)), running agent steps"

    # ── Phase 1: Independent steps (no dependencies on each other) ──

    # Step 8: Run meeting-prepper agent (Meeting Prep section)
    step "Step 8/12: meeting-prepper agent"
    export AGENT_PIPELINE_STEP="step_8_meeting_prepper"
    if [ -f "$AGENT_RUNNER" ]; then
        if section_is_fresh "Auto-generated by meeting-prepper"; then
            log "SKIP: meeting-prepper section is fresh (<2h old)"
        else
            (cd "$VAULT_DIR" && "$UV" run "$AGENT_RUNNER" \
                meeting-prepper \
                "Prepare meeting context for today's meetings and write the Meeting Prep section." \
                2>&1) \
                || log "WARNING: meeting-prepper agent had errors (non-fatal)"
        fi
    else
        log "WARNING: $AGENT_RUNNER not found, skipping meeting-prepper"
    fi

    # Step 9: Extract and summarize today's conversations (Slack DMs + email)
    step "Step 9/12: conversation-summarizer"
    export AGENT_PIPELINE_STEP="step_9_conversation_summarizer"
    CONV_EXTRACT="$SKILL_DIR/scripts/extract_conversations.py"
    if [ -f "$CONV_EXTRACT" ]; then
        CONV_JSON=$("$UV" run "$CONV_EXTRACT" "$VAULT_DIR" 2>&1 | tee /dev/stderr | grep -v '^\[' | grep -v '^WARNING' | grep -v '^Extract' | tail -1) \
            || log "WARNING: conversation extraction had errors (non-fatal)"
        if [ -n "$CONV_JSON" ] && [ -f "$CONV_JSON" ]; then
            (cd "$VAULT_DIR" && "$UV" run "$AGENT_RUNNER" \
                conversation-summarizer \
                "Summarize conversations from $CONV_JSON into today's daily note." \
                2>&1) \
                || log "WARNING: conversation-summarizer agent had errors (non-fatal)"
        else
            log "WARNING: conversation extraction produced no output file, skipping summarizer"
        fi
    else
        log "WARNING: $CONV_EXTRACT not found, skipping conversation sync"
    fi

    # ── Phase 2: Project updater (writes to Projects/*.md, independent of phase 1) ──

    # Step 10: Run project-updater driver (batch mode: Python discovery + LLM writing)
    step "Step 10/12: project-updater driver"
    export AGENT_PIPELINE_STEP="step_10_project_updater"
    PROJECT_DRIVER="$SKILL_DIR/scripts/project_update_driver.py"
    if [ -f "$PROJECT_DRIVER" ]; then
        if section_is_fresh "Auto-generated by project-updater"; then
            log "SKIP: project-updater section is fresh (<2h old)"
        else
            (cd "$VAULT_DIR" && "$UV" run "$PROJECT_DRIVER" \
                2>&1) \
                || log "WARNING: project-updater driver had errors (non-fatal)"
        fi
    else
        log "WARNING: $PROJECT_DRIVER not found, skipping project-updater"
    fi

    # ── Phase 3: Dependent steps (need phase 1 + 2 complete) ──

    # Step 11: Run daily-summarizer agent (Active Projects + Upcoming Deadlines)
    # Depends on: project-updater (reads updated project notes)
    step "Step 11/12: daily-summarizer agent"
    export AGENT_PIPELINE_STEP="step_11_daily_summarizer"
    if [ -f "$AGENT_RUNNER" ]; then
        if section_is_fresh "Auto-updated by daily-summarizer"; then
            log "SKIP: daily-summarizer section is fresh (<2h old)"
        else
            (cd "$VAULT_DIR" && "$UV" run "$AGENT_RUNNER" \
                daily-summarizer \
                "Build the Active Projects and Upcoming Deadlines sections for today's daily note." \
                2>&1) \
                || log "WARNING: daily-summarizer agent had errors (non-fatal)"
        fi
    else
        log "WARNING: $AGENT_RUNNER not found, skipping daily-summarizer"
    fi

    # Step 12: Run daily-curator agent (Digest + Action Items)
    # Depends on: meeting-prepper, conversation-summarizer, daily-summarizer
    step "Step 12/12: daily-curator agent"
    export AGENT_PIPELINE_STEP="step_12_daily_curator"
    if [ -f "$AGENT_RUNNER" ]; then
        if section_is_fresh "Auto-curated on"; then
            log "SKIP: daily-curator section is fresh (<2h old)"
        else
            (cd "$VAULT_DIR" && "$UV" run "$AGENT_RUNNER" \
                daily-curator \
                "Curate today's daily note: write the Digest and Action Items sections." \
                2>&1) \
                || log "WARNING: daily-curator agent had errors (non-fatal)"
        fi
    else
        log "WARNING: $AGENT_RUNNER not found, skipping daily-curator"
    fi
else
    log "Agent window not active (hour=$(date +%H)), skipping agent steps 8-12"
fi

log ""
log "=== Daily Sync All: Finished ==="
