#!/bin/bash
# Sync health watchdog — runs every 30 minutes via launchd.
# Reads the sync log and today's daily note, writes sync-status.md to the vault.

set -u

_find_vault_root() {
    local dir
    dir="$(cd "$(dirname "$0")" && pwd)"
    while [ "$dir" != "/" ]; do
        [ -d "$dir/.obsidian" ] && echo "$dir" && return
        dir="$(dirname "$dir")"
    done
    echo "ERROR: Could not find vault root (no .obsidian/ directory found)" >&2
    exit 1
}
VAULT_DIR="${VAULT_DIR:-$(_find_vault_root)}"
LOG_FILE="$HOME/Library/Logs/daily-work-sync/stdout.log"
STATUS_FILE="$VAULT_DIR/sync-status.md"

TODAY=$(date +%Y-%m-%d)
YEAR=$(date +%Y)
MONTH_NUM=$(date +%m)
MONTH_NAME=$(date +%B)
DAY_NAME=$(date +%A)
NOW=$(date "+%Y-%m-%d %H:%M")

DAILY_NOTE="$VAULT_DIR/daily/$YEAR/$MONTH_NUM-$MONTH_NAME/$TODAY-$DAY_NAME.md"

# --- Parse log for last run ---
LAST_START=$(grep "=== Daily Sync All: Started ===" "$LOG_FILE" 2>/dev/null | tail -1 | grep -oE '[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}' || echo "unknown")
LAST_FINISH=$(grep "=== Daily Sync All: Finished ===" "$LOG_FILE" 2>/dev/null | tail -1 | grep -oE '[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}' || echo "unknown")
LAST_WARNINGS=$(grep -c "WARNING:" "$LOG_FILE" 2>/dev/null || echo "0")

# Check if sync is currently running
if ps aux | grep sync_all_sources.sh | grep -qv grep; then
    SYNC_RUNNING=true
    RUNNING_SINCE=$(ps -o lstart= -p $(pgrep -f sync_all_sources.sh) 2>/dev/null | head -1 | xargs || echo "unknown")
else
    SYNC_RUNNING=false
    RUNNING_SINCE=""
fi

# How stale is the last finish?
STALE_HOURS=""
STALE_STATUS="unknown"
if [ "$LAST_FINISH" != "unknown" ]; then
    LAST_FINISH_EPOCH=$(date -j -f "%Y-%m-%d %H:%M:%S" "$LAST_FINISH" "+%s" 2>/dev/null || echo "0")
    NOW_EPOCH=$(date +%s)
    STALE_SECS=$(( NOW_EPOCH - LAST_FINISH_EPOCH ))
    STALE_HOURS=$(( STALE_SECS / 3600 ))
    if $SYNC_RUNNING; then
        STALE_STATUS="running"
    elif [ "$STALE_HOURS" -lt 2 ]; then
        STALE_STATUS="ok"
    elif [ "$STALE_HOURS" -lt 5 ]; then
        STALE_STATUS="warn"
    else
        STALE_STATUS="stale"
    fi
fi

# --- Check today's daily note ---
NOTE_EXISTS=false
HAS_MEETINGS=false
HAS_MEETING_PREP=false
HAS_DIGEST=false
HAS_ACTION_ITEMS=false
HAS_ACTIVE_PROJECTS=false

if [ -f "$DAILY_NOTE" ]; then
    NOTE_EXISTS=true
    grep -q "### Meetings" "$DAILY_NOTE" && grep -qv "^### Meetings$" <(grep -A2 "### Meetings" "$DAILY_NOTE") && HAS_MEETINGS=true || true
    grep -q "Auto-generated by project-tracker" "$DAILY_NOTE" && HAS_MEETING_PREP=true || true
    grep -q "Auto-curated on" "$DAILY_NOTE" && HAS_DIGEST=true || true
    grep -q "^\- \[" "$DAILY_NOTE" && HAS_ACTION_ITEMS=true || true
    grep -q "Auto-updated by project-tracker" "$DAILY_NOTE" && HAS_ACTIVE_PROJECTS=true || true
fi

# --- Build status indicators ---
status_icon() {
    case "$1" in
        ok)      echo "✅" ;;
        warn)    echo "⚠️" ;;
        stale)   echo "🔴" ;;
        running) echo "🔄" ;;
        *)       echo "❓" ;;
    esac
}

check_icon() {
    $1 && echo "✅" || echo "❌"
}

SYNC_ICON=$(status_icon "$STALE_STATUS")

if $SYNC_RUNNING; then
    SYNC_LINE="🔄 **Running now** (started $RUNNING_SINCE)"
elif [ "$STALE_STATUS" = "ok" ]; then
    SYNC_LINE="✅ Last run: \`$LAST_FINISH\` (${STALE_HOURS}h ago)"
elif [ "$STALE_STATUS" = "warn" ]; then
    SYNC_LINE="⚠️ Last run: \`$LAST_FINISH\` (${STALE_HOURS}h ago — running behind)"
elif [ "$STALE_STATUS" = "stale" ]; then
    SYNC_LINE="🔴 Last run: \`$LAST_FINISH\` (${STALE_HOURS}h ago — **stale**)"
else
    SYNC_LINE="❓ No completed runs found in log"
fi

# --- Write status note ---
cat > "$STATUS_FILE" <<EOF
---
updated: $NOW
---

# Sync Status

> [!info] Last checked: $NOW

## Pipeline Health

$SYNC_LINE
- Last start: \`$LAST_START\`
- Warnings in log: $LAST_WARNINGS

## Today's Daily Note ($TODAY)

| Section | Status |
|---------|--------|
| Note exists | $(check_icon $NOTE_EXISTS) |
| Meetings table | $(check_icon $HAS_MEETINGS) |
| Meeting Prep | $(check_icon $HAS_MEETING_PREP) |
| Digest | $(check_icon $HAS_DIGEST) |
| Action Items | $(check_icon $HAS_ACTION_ITEMS) |
| Active Projects | $(check_icon $HAS_ACTIVE_PROJECTS) |

## Quick Links

- [[daily/$YEAR/$MONTH_NUM-$MONTH_NAME/$TODAY-$DAY_NAME|Today's Note]]
- [Sync log](file://$HOME/Library/Logs/daily-work-sync/stdout.log)

EOF

echo "[$NOW] Watchdog ran — sync: $STALE_STATUS, digest: $HAS_DIGEST, action items: $HAS_ACTION_ITEMS"
